StarStuff.Web/Areas/Astronomer/Models/Discoveries/DiscoveryDetailsViewModel.cs
namespace StarStuff.Web.Areas.Astronomer.Models.Discoveries
{
    using Services.Areas.Astronomer.Models.Astronomers;
    using Services.Areas.Astronomer.Models.Discoveries;
    using Services.Areas.Astronomer.Models.Planets;
    using Services.Areas.Astronomer.Models.Stars;
    using System.Collections.Generic;

    public class DiscoveryDetailsViewModel
    {
        public bool IsPioneer { get; set; }

        public bool IsObserver { get; set; }

        public DiscoveryDetailsServiceModel Discovery { get; set; }

        public IEnumerable<ListStarsServiceModel> Stars { get; set; }

        public IEnumerable<ListPlanetsServiceModel> Planets { get; set; }

        public IEnumerable<AstronomerServiceModel> Pioneers { get; set; }

        public IEnumerable<AstronomerServiceModel> Observers { get; set; }
    }
}

StarStuff.Web/Areas/Astronomer/Models/Discoveries/DiscoveryFormViewModel.cs
namespace StarStuff.Web.Areas.Astronomer.Models.Discoveries
{
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Services.Areas.Astronomer.Models.Discoveries;
    using Services.Areas.Astronomer.Models.Stars;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class DiscoveryFormViewModel
    {
        public DiscoveryFormServiceModel Discovery { get; set; }

        public StarFormServiceModel Star { get; set; }

        [Display(Name = "Telescope")]
        public int TelescopeId { get; set; }

        [Display(Name = "Discoverers")]
        public IEnumerable<int> AstronomerIds { get; set; }

        public IEnumerable<SelectListItem> Telescopes { get; set; }

        public IEnumerable<SelectListItem> Astronomers { get; set; }
    }
}

StarStuff.Web/Areas/Astronomer/Models/Discoveries/ListDiscoveriesViewModel.cs
namespace StarStuff.Web.Areas.Astronomer.Models.Discoveries
{
    using Infrastructure.Helpers;
    using Services.Areas.Astronomer.Models.Discoveries;
    using System.Collections.Generic;

    public class ListDiscoveriesViewModel : BasePageViewModel
    {
        public string Search { get; set; }

        public bool? Confirmed { get; set; }

        public IEnumerable<ListDiscoveriesServiceModel> Discoveries { get; set; }
    }
}

StarStuff.Web/Areas/Astronomer/Models/Discoveries/ListMyDiscoveriesViewModel.cs
namespace StarStuff.Web.Areas.Astronomer.Models.Discoveries
{
    public class ListMyDiscoveriesViewModel : ListDiscoveriesViewModel
    {
        public string Astronomer { get; set; }
    }
}

StarStuff.Web/Areas/Astronomer/Controllers/DiscoveriesController.cs
namespace StarStuff.Web.Areas.Astronomer.Controllers
{
    using Data.Models;
    using Infrastructure;
    using Infrastructure.Extensions;
    using Infrastructure.Filters;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Models.Discoveries;
    using Services;
    using Services.Areas.Astronomer;
    using Services.Areas.Astronomer.Models.Astronomers;
    using Services.Areas.Astronomer.Models.Discoveries;
    using Services.Areas.Moderator;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public class DiscoveriesController : BaseAstronomerController
    {
        private const int DiscoveriesPerPage = 20;
        private const string Discovery = "Discovery";
        private const string Star = "Star";
        private const string StarSystem = "Star System";

        private readonly IDiscoveryService discoveryService;
        private readonly IPlanetService planetService;
        private readonly IStarService starService;
        private readonly ITelescopeService telescopeService;
        private readonly IUserService userService;
        private readonly UserManager<User> userManager;

        public DiscoveriesController(
            IDiscoveryService discoveryService,
            IPlanetService planetService,
            IStarService starService,
            ITelescopeService telescopeService,
            IUserService userService,
            UserManager<User> userManager)
        {
            this.discoveryService = discoveryService;
            this.planetService = planetService;
            this.starService = starService;
            this.telescopeService = telescopeService;
            this.userService = userService;
            this.userManager = userManager;
        }

        public IActionResult Details(int id)
        {
            int userId = int.Parse(this.userManager.GetUserId(User));

            DiscoveryDetailsViewModel model = new DiscoveryDetailsViewModel
            {
                IsPioneer = this.discoveryService.IsPioneer(id, userId),
                IsObserver = this.discoveryService.IsObserver(id, userId),
                Discovery = this.discoveryService.Details(id),
                Stars = this.starService.Stars(id),
                Planets = this.planetService.Planets(id),
                Pioneers = this.discoveryService.Pioneers(id),
                Observers = this.discoveryService.Observers(id)
            };

            if (model.Discovery == null)
            {
                return BadRequest();
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Confirm(int id)
        {
            int astronomerId = int.Parse(this.userManager.GetUserId(User));

            bool success = this.discoveryService.Confirm(id, astronomerId);

            if (!success)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Details), new { id });
        }

        public IActionResult Create()
        {
            int astronomerId = int.Parse(this.userManager.GetUserId(User));

            DiscoveryFormViewModel model = new DiscoveryFormViewModel();
            this.PopulateCreateViewModel(astronomerId, model);

            return View(model);
        }

        [HttpPost]
        [Log(nameof(Create), Discoveries)]
        public IActionResult Create(DiscoveryFormViewModel model)
        {
            int astronomerId = int.Parse(this.userManager.GetUserId(User));

            if (!ModelState.IsValid)
            {
                this.PopulateCreateViewModel(astronomerId, model);
                return View(model);
            }

            if (this.discoveryService.Exists(model.Discovery.StarSystem))
            {
                this.PopulateCreateViewModel(astronomerId, model);
                TempData.AddErrorMessage(string.Format(WebConstants.EntryExists, StarSystem));
                return View(model);
            }

            if (this.starService.Exists(model.Star.Name))
            {
                this.PopulateCreateViewModel(astronomerId, model);
                TempData.AddErrorMessage(string.Format(WebConstants.EntryExists, Star));
                return View(model);
            }

            int discoveryId = this.discoveryService.Create(
                model.Discovery.StarSystem,
                model.Discovery.Distance,
                model.TelescopeId,
                astronomerId,
                model.AstronomerIds);

            if (discoveryId <= 0)
            {
                return BadRequest();
            }

            bool success = this.starService.Create(discoveryId, model.Star.Name, model.Star.Temperature);

            if (!success)
            {
                this.discoveryService.Delete(discoveryId);
                return BadRequest();
            }

            TempData.AddSuccessMessage(string.Format(WebConstants.SuccessfullEntityOperation, Discovery, WebConstants.Added));

            return RedirectToAction(nameof(Details), new { id = discoveryId });
        }

        public IActionResult Edit(int id)
        {
            DiscoveryFormServiceModel model = this.discoveryService.GetForm(id);

            if (model == null)
            {
                return BadRequest();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateModelState]
        [Log(nameof(Edit), Discoveries)]
        public IActionResult Edit(int id, DiscoveryFormServiceModel model)
        {
            string oldName = this.discoveryService.GetName(id);

            if (oldName == null)
            {
                return BadRequest();
            }

            string newName = model.StarSystem;

            if (this.discoveryService.Exists(newName)
                && oldName != newName)
            {
                TempData.AddErrorMessage(string.Format(WebConstants.EntryExists, StarSystem));
                return View(model);
            }

            bool success = this.discoveryService.Edit(id, model.StarSystem, model.Distance);

            if (!success)
            {
                return BadRequest();
            }

            TempData.AddSuccessMessage(string.Format(WebConstants.SuccessfullEntityOperation, Discovery, WebConstants.Edited));

            return RedirectToAction(nameof(Details), new { id });
        }

        public IActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        [ActionName(nameof(Delete))]
        [Log(nameof(Delete), Discoveries)]
        public IActionResult DeletePost(int id)
        {
            bool success = this.discoveryService.Delete(id);

            if (!success)
            {
                return BadRequest();
            }

            TempData.AddSuccessMessage(string.Format(WebConstants.SuccessfullEntityOperation, Discovery, WebConstants.Deleted));

            return RedirectToAction(nameof(All));
        }

        public IActionResult Mine(int page, string search, bool? confirmed, string astronomer)
        {
            if (page <= 0)
            {
                page = 1;
            }

            bool astronomerParsed = Enum.TryParse(astronomer, true, out AstronomerType astronomerType);

            if (!astronomerParsed)
            {
                astronomerType = AstronomerType.All;
            }

            int astronomerId = int.Parse(this.userManager.GetUserId(User));
            int totalDiscoveries = this.discoveryService.Total(search, confirmed, astronomerId, astronomerType);

            ListMyDiscoveriesViewModel model = new ListMyDiscoveriesViewModel
            {
                Confirmed = confirmed,
                CurrentPage = page,
                Search = search,
                Astronomer = astronomerType.ToString(),
                TotalEntries = totalDiscoveries,
                EntriesPerPage = DiscoveriesPerPage,
                Discoveries = this.discoveryService.All(page, DiscoveriesPerPage, search, confirmed, astronomerId, astronomerType)
            };

            return View(model);
        }

        public IActionResult All(int page, string search, bool? confirmed)
        {
            if (page <= 0)
            {
                page = 1;
            }

            int totalDiscoveries = this.discoveryService.Total(search, confirmed);

            ListDiscoveriesViewModel model = new ListDiscoveriesViewModel
            {
                Confirmed = confirmed,
                CurrentPage = page,
                Search = search,
                TotalEntries = totalDiscoveries,
                EntriesPerPage = DiscoveriesPerPage,
                Discoveries = this.discoveryService.All(page, DiscoveriesPerPage, search, confirmed)
            };

            return View(model);
        }

        private void PopulateCreateViewModel(int astronomerId, DiscoveryFormViewModel model)
        {
            model.Astronomers = this.GetAstronomers(astronomerId);
            model.Telescopes = this.GetTelescopes();
        }

        private IEnumerable<SelectListItem> GetAstronomers(int astronomerId)
        {
            return this.userService
                .Astronomers(astronomerId)
                .Select(a => new SelectListItem
                {
                    Text = $"{a.FirstName} {a.LastName}",
                    Value = a.Id.ToString()
                });
        }

        private IEnumerable<SelectListItem> GetTelescopes()
        {
            return this.telescopeService
                .TelescopeDropdown()
                .Select(t => new SelectListItem
                {
                    Text = t.Name,
                    Value = t.Id.ToString()
                });
        }
    }
}

StarStuff.Web/Controllers/TelescopesController.cs
namespace StarStuff.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Models.Telescopes;
    using Services.Areas.Moderator;
    using Services.Areas.Moderator.Models.Telescopes;

    public class TelescopesController : Controller
    {
        private const int TelescopesPerPage = 10;

        private readonly ITelescopeService telescopeService;

        public TelescopesController(ITelescopeService telescopeService)
        {
            this.telescopeService = telescopeService;
        }

        public IActionResult Details(int id)
        {
            TelescopeDetailsServiceModel model = this.telescopeService.Details(id);

            if (model == null)
            {
                return BadRequest();
            }

            return View(model);
        }

        public IActionResult All(int page)
        {
            if (page <= 0)
            {
                page = 1;
            }

            int totalTelescopes = this.telescopeService.Total();

            ListTelescopesViewModel model = new ListTelescopesViewModel
            {
                CurrentPage = page,
                TotalEntries = totalTelescopes,
                EntriesPerPage = TelescopesPerPage,
                Telescopes = this.telescopeService.All(page, TelescopesPerPage)
            };

            return View(model);
        }
    }
}

StarStuff.Web/Areas/Astronomer/Views/Discoveries/All.cshtml
@model ListDiscoveriesViewModel

@{
    ViewData["Title"] = $"{(Model.Search != null ? string.Empty : "All ")}{(Model.Confirmed == null ? string.Empty : Model.Confirmed.Value ? "Confirmed " : "Not Confirmed ")}Discoveries";
    string previouseDisabled = Model.CurrentPage == 1 ? "disabled" : string.Empty;
    string nextDisabled = Model.CurrentPage == Model.TotalPages ? "disabled" : string.Empty;
    string search = Model.Search != null ? Model.Search : string.Empty;
}

<div class="row">
    <h2>@ViewData["Title"]</h2>
    <form class="form-inline" asp-area="Astronomer" asp-controller="Discoveries" asp-action="All">
        <input type="hidden" asp-for="Confirmed" />
        <input class="form-control" asp-for="Search" placeholder="Search..." />
        <input class="btn btn-success" type="submit" value="Search" />
    </form>
    <br />
    <a class="btn btn-primary" asp-area="Astronomer" asp-controller="Discoveries" asp-action="All">All</a>
    <a class="btn btn-primary" asp-area="Astronomer" asp-controller="Discoveries" asp-action="All" asp-route-confirmed="true">Confirmed</a>
    <a class="btn btn-primary" asp-area="Astronomer" asp-controller="Discoveries" asp-action="All" asp-route-confirmed="false">Not Confirmed</a>
    @Html.Partial("_DiscoveriesTable", Model.Discoveries)
</div>
@if (Model.Discoveries.Any())
{
    <div class="row">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link @previouseDisabled" asp-area="Astronomer" asp-controller="Discoveries" asp-action="All" asp-route-page="@Model.PrevPage" asp-route-search="@search" asp-route-confirmed="@Model.Confirmed" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            @for (int i = Model.FirstPage; i <= Model.LastPage; i++)
            {
                <li class="page-item @(Model.CurrentPage == i ? "active" : string.Empty)">
                    <a class="page-link @(Model.CurrentPage == i ? "disabled" : string.Empty)" asp-area="Astronomer" asp-controller="Discoveries" asp-action="All" asp-route-page="@i" asp-route-search="@search" asp-route-confirmed="@Model.Confirmed">@i</a>
                </li>
            }
            <li class="page-item">
                <a class="page-link @nextDisabled" asp-area="Astronomer" asp-controller="Discoveries" asp-action="All" asp-route-page="@Model.NextPage" asp-route-search="@search" asp-route-confirmed="@Model.Confirmed" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    </div>
}

StarStuff.Web/Areas/Astronomer/Views/Discoveries/Create.cshtml
@model DiscoveryFormViewModel
@{
    ViewData["Title"] = "Add Discovery";
}

<div class="row">
    <div class="col-md-offset-2 col-md-4 ">
        <h2>@ViewData["Title"]</h2>
        <form method="post">
            <hr />
            <div class="form-group">
                <label asp-for="Discovery.StarSystem"></label>
                <input asp-for="Discovery.StarSystem" class="form-control" />
                <span asp-validation-for="Discovery.StarSystem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discovery.Distance"></label>
                <input asp-for="Discovery.Distance" class="form-control" />
                <span asp-validation-for="Discovery.Distance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Star.Name"></label>
                <input asp-for="Star.Name" class="form-control" />
                <span asp-validation-for="Star.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Star.Temperature"></label>
                <input asp-for="Star.Temperature" class="form-control" />
                <span asp-validation-for="Star.Temperature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelescopeId"></label>
                <select asp-for="TelescopeId" asp-items="@Model.Telescopes" class="form-control"></select>
                <span asp-validation-for="TelescopeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AstronomerIds"></label>
                <select asp-for="AstronomerIds" asp-items="@Model.Astronomers" multiple class="form-control"></select>
                <span asp-validation-for="AstronomerIds" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-default">Save Discovery</button>
        </form>
    </div>

    @section Scripts {
        @await Html.PartialAsync("_ValidationScriptsPartial")
    }
</div>

StarStuff.Web/Areas/Astronomer/Views/Discoveries/Delete.cshtml
@{
    ViewData["Title"] = "Delete Discovery";
}

<h2>@ViewData["Title"]</h2>

<form method="post">
    <hr />
    Are you sure you want to delete this Discovery? <input class="btn btn-danger" type="submit" value="Delete Discovery" />
</form>

StarStuff.Web/Areas/Astronomer/Views/Discoveries/Details.cshtml
@model DiscoveryDetailsViewModel
@{
    ViewData["Title"] = "Discovery Details";
}

<div class="row">
    <h2>@ViewData["Title"]</h2>
    <h3>Star System Name: @Model.Discovery.StarSystem</h3>
    <h3>Distance From Earth: @Model.Discovery.Distance Light Years</h3>
    <h3>Telescope Name: <a asp-area="" asp-controller="Telescopes" asp-action="Details" asp-route-id="@Model.Discovery.TelescopeId">@Model.Discovery.TelescopeName</a></h3>
    <h3>Discovery Date: @Model.Discovery.DateMade.ToShortDateString()</h3>
    <h4>
        Confirmed:
        @if (Model.Discovery.IsConfirmed)
        {
            <span class="glyphicon glyphicon-ok text-success"></span>
        }
        else
        {
            <span class="glyphicon glyphicon-remove text-danger"></span>
        }
    </h4>
    <h4>
        Publication:
        @if (Model.Discovery.HasPublication)
        {
            <span class="glyphicon glyphicon-ok text-success"></span>
        }
        else
        {
            <span class="glyphicon glyphicon-remove text-danger"></span>
        }
    </h4>
    @if (!(Model.IsObserver || Model.IsPioneer) && !Model.Discovery.IsConfirmed)
    {
        <form method="post" asp-area="Astronomer" asp-controller="Discoveries" asp-action="Confirm" asp-route-id="@Model.Discovery.Id">
            <input class="btn btn-success btn-sm" type="submit" value="Confirm" />
        </form>
    }
    <div class="pull-right">
        @if (Model.IsPioneer)
        {
            <a asp-area="Astronomer" asp-controller="Discoveries" asp-action="Edit" asp-route-id="@Model.Discovery.Id" class="btn btn-warning btn-sm">Edit</a>
        }

        @if (User.IsInRole(WebConstants.ModeratorRole))
        {
            <a asp-area="Astronomer" asp-controller="Discoveries" asp-action="Delete" asp-route-id="@Model.Discovery.Id" class="btn btn-danger btn-sm">Delete</a>
        }
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-6">
        <h4>Stars</h4>
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Temperature in Kelvin</th>
                    @if (Model.IsPioneer)
                    {
                        <th>Actions</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var star in Model.Stars)
                {
                    <tr>
                        <td>@star.Name</td>
                        <td>@star.Temperature</td>
                        @if (Model.IsPioneer)
                        {
                            <td>
                                <a class="btn btn-warning btn-xs" asp-area="Astronomer" asp-controller="Stars" asp-action="Edit" asp-route-id="@star.Id" asp-route-discoveryId="@Model.Discovery.Id">Edit</a>
                                @if (Model.Stars.Count() > 1)
                                {
                                    <a class="btn btn-danger btn-xs" asp-area="Astronomer" asp-controller="Stars" asp-action="Delete" asp-route-id="@star.Id" asp-route-discoveryId="@Model.Discovery.Id">Delete</a>
                                }
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        @if (Model.IsPioneer && Model.Stars.Count() < DataConstants.DiscoveryConstants.MaxStarsPerDiscovery)
        {
            <a class="btn btn-success btn-sm" asp-area="Astronomer" asp-controller="Stars" asp-action="Create" asp-route-id="@Model.Discovery.Id">Add Star</a>
        }
    </div>
    <div class="col-md-6">
        <h4>Planets</h4>
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Relative Mass</th>
                    @if (Model.IsPioneer)
                    {
                        <th>Actions</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var planet in Model.Planets)
                {
                    <tr>
                        <td>@planet.Name</td>
                        <td>@planet.Mass</td>
                        @if (Model.IsPioneer)
                        {
                            <td>
                                <a class="btn btn-warning btn-xs" asp-area="Astronomer" asp-controller="Planets" asp-action="Edit" asp-route-id="@planet.Id" asp-route-discoveryId="@Model.Discovery.Id">Edit</a>
                                <a class="btn btn-danger btn-xs" asp-area="Astronomer" asp-controller="Planets" asp-action="Delete" asp-route-id="@planet.Id" asp-route-discoveryId="@Model.Discovery.Id">Delete</a>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        @if (Model.IsPioneer && Model.Stars.Any())
        {
            <a class="btn btn-success btn-sm" asp-area="Astronomer" asp-controller="Planets" asp-action="Create" asp-route-id="@Model.Discovery.Id">Add Planet</a>
        }
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-6">
        <h4>Pioneers</h4>
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pioneer in Model.Pioneers)
                {
                    <tr>
                        <td>@pioneer.FirstName</td>
                        <td>@pioneer.LastName</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <h4>Observers</h4>
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var observer in Model.Observers)
                {
                    <tr>
                        <td>@observer.FirstName</td>
                        <td>@observer.LastName</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

StarStuff.Web/Areas/Astronomer/Views/Discoveries/Mine.cshtml
@model ListMyDiscoveriesViewModel

@{
    ViewData["Title"] = $"My {(Model.Confirmed == null ? string.Empty : Model.Confirmed.Value ? "Confirmed " : "Not Confirmed ")}Discoveries {(Model.Astronomer == "All" ? string.Empty : Model.Astronomer == "Pioneer" ? "as Pioneer" : "as Observer")}";
    string previouseDisabled = Model.CurrentPage == 1 ? "disabled" : string.Empty;
    string nextDisabled = Model.CurrentPage == Model.TotalPages ? "disabled" : string.Empty;
}

<div class="row">
    <h2>@ViewData["Title"]</h2>
    <form class="form-inline" asp-area="Astronomer" asp-controller="Discoveries" asp-action="Mine">
        <input type="hidden" asp-for="Confirmed" />
        <input type="hidden" asp-for="Astronomer" />
        <input class="form-control" asp-for="Search" placeholder="Search..." />
        <input class="btn btn-success" type="submit" value="Search" />
    </form>
    <br />
    <a class="btn btn-primary" asp-area="Astronomer" asp-controller="Discoveries" asp-action="Mine">All</a>
    <a class="btn btn-primary" asp-area="Astronomer" asp-controller="Discoveries" asp-action="Mine" asp-route-confirmed="true" asp-route-astronomer="@Model.Astronomer">Confirmed</a>
    <a class="btn btn-primary" asp-area="Astronomer" asp-controller="Discoveries" asp-action="Mine" asp-route-confirmed="false" asp-route-astronomer="@Model.Astronomer">Not Confirmed</a>
    <a class="btn btn-primary" asp-area="Astronomer" asp-controller="Discoveries" asp-action="Mine" asp-route-confirmed="@Model.Confirmed" asp-route-astronomer="pioneer">Pioneer</a>
    <a class="btn btn-primary" asp-area="Astronomer" asp-controller="Discoveries" asp-action="Mine" asp-route-confirmed="@Model.Confirmed" asp-route-astronomer="observer">Observer</a>
    @Html.Partial("_DiscoveriesTable", Model.Discoveries)
</div>
@if (Model.Discoveries.Any())
{
    <div class="row">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link @previouseDisabled" asp-area="Astronomer" asp-controller="Discoveries" asp-action="Mine" asp-route-page="@Model.PrevPage" asp-route-search="@Model.Search" asp-route-confirmed="@Model.Confirmed" asp-route-astronomer="@Model.Astronomer" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            @for (int i = Model.FirstPage; i <= Model.LastPage; i++)
            {
                <li class="page-item @(Model.CurrentPage == i ? "active" : string.Empty)">
                    <a class="page-link @(Model.CurrentPage == i ? "disabled" : string.Empty)" asp-area="Astronomer" asp-controller="Discoveries" asp-action="Mine" asp-route-page="@i" asp-route-search="@Model.Search" asp-route-confirmed="@Model.Confirmed" asp-route-astronomer="@Model.Astronomer">@i</a>
                </li>
            }
            <li class="page-item">
                <a class="page-link @nextDisabled" asp-area="Astronomer" asp-controller="Discoveries" asp-action="Mine" asp-route-page="@Model.NextPage" asp-route-search="@Model.Search" asp-route-confirmed="@Model.Confirmed" asp-route-astronomer="@Model.Astronomer" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    </div>
}

StarStuff.Web/Areas/Astronomer/Views/Discoveries/_DiscoveriesTable.cshtml
@model IEnumerable<ListDiscoveriesServiceModel>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>Star System</th>
            <th>Distance</th>
            <th class="text-center">Stars</th>
            <th class="text-center">Planets</th>
            <th class="text-center">Is Confirmed</th>
            <th class="text-center">Has Publication</th>
            <th>Date Made</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var discovery in Model)
        {
            <tr>
                <td>@discovery.StarSystem</td>
                <td>@discovery.Distance</td>
                <td class="text-center">@discovery.Stars</td>
                <td class="text-center">@discovery.Planets</td>
                <td class="text-center">
                    @if (discovery.IsConfirmed)
                    {
                        <span class="glyphicon glyphicon-ok text-success"></span>
                    }
                    else
                    {
                        <span class="glyphicon glyphicon-remove text-danger"></span>
                    }
                </td>
                <td class="text-center">
                    @if (discovery.HasPublication)
                    {
                        <span class="glyphicon glyphicon-ok text-success"></span>
                    }
                    else
                    {
                        <span class="glyphicon glyphicon-remove text-danger"></span>
                    }
                </td>
                <td>@discovery.DateMade.ToShortDateString()</td>
                <td>
                    <a class="btn btn-primary" asp-area="Astronomer" asp-controller="Discoveries" asp-action="Details" asp-route-id="@discovery.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>